// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gate.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "gate.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace gate {

namespace {

const ::google::protobuf::Descriptor* GateConnection_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  GateConnection_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* GateConnection_EventType_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* GateConnection_ConnectionCloseReason_descriptor_ = NULL;
const ::google::protobuf::Descriptor* AuthReq_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  AuthReq_reflection_ = NULL;
const ::google::protobuf::Descriptor* AuthRsp_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  AuthRsp_reflection_ = NULL;
const ::google::protobuf::Descriptor* GateAuth_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  GateAuth_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* GateAuth_GateAuthCMD_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_gate_2eproto() {
  protobuf_AddDesc_gate_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "gate.proto");
  GOOGLE_CHECK(file != NULL);
  GateConnection_descriptor_ = file->message_type(0);
  static const int GateConnection_offsets_[6] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GateConnection, event_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GateConnection, idx_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GateConnection, ip_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GateConnection, port_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GateConnection, reason_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GateConnection, uid_),
  };
  GateConnection_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      GateConnection_descriptor_,
      GateConnection::default_instance_,
      GateConnection_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GateConnection, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GateConnection, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(GateConnection));
  GateConnection_EventType_descriptor_ = GateConnection_descriptor_->enum_type(0);
  GateConnection_ConnectionCloseReason_descriptor_ = GateConnection_descriptor_->enum_type(1);
  AuthReq_descriptor_ = file->message_type(1);
  static const int AuthReq_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AuthReq, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AuthReq, auth_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AuthReq, token_),
  };
  AuthReq_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      AuthReq_descriptor_,
      AuthReq::default_instance_,
      AuthReq_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AuthReq, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AuthReq, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(AuthReq));
  AuthRsp_descriptor_ = file->message_type(2);
  static const int AuthRsp_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AuthRsp, result_),
  };
  AuthRsp_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      AuthRsp_descriptor_,
      AuthRsp::default_instance_,
      AuthRsp_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AuthRsp, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AuthRsp, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(AuthRsp));
  GateAuth_descriptor_ = file->message_type(3);
  static const int GateAuth_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GateAuth, cmd_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GateAuth, authreq_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GateAuth, authrsp_),
  };
  GateAuth_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      GateAuth_descriptor_,
      GateAuth::default_instance_,
      GateAuth_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GateAuth, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GateAuth, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(GateAuth));
  GateAuth_GateAuthCMD_descriptor_ = GateAuth_descriptor_->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_gate_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    GateConnection_descriptor_, &GateConnection::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    AuthReq_descriptor_, &AuthReq::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    AuthRsp_descriptor_, &AuthRsp::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    GateAuth_descriptor_, &GateAuth::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_gate_2eproto() {
  delete GateConnection::default_instance_;
  delete GateConnection_reflection_;
  delete AuthReq::default_instance_;
  delete AuthReq_reflection_;
  delete AuthRsp::default_instance_;
  delete AuthRsp_reflection_;
  delete GateAuth::default_instance_;
  delete GateAuth_reflection_;
}

void protobuf_AddDesc_gate_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\ngate.proto\022\004gate\"\340\002\n\016GateConnection\022-\n"
    "\005event\030\001 \002(\0162\036.gate.GateConnection.Event"
    "Type\022\013\n\003idx\030\002 \002(\r\022\n\n\002ip\030\003 \001(\r\022\014\n\004port\030\004 "
    "\001(\r\022\016\n\006reason\030\005 \001(\r\022\013\n\003uid\030\006 \001(\004\"A\n\tEven"
    "tType\022\023\n\017EVENT_CONNECTED\020\001\022\017\n\013EVENT_CLOS"
    "E\020\002\022\016\n\nEVENT_DATA\020\003\"\227\001\n\025ConnectionCloseR"
    "eason\022\037\n\033CONNECTION_CLOSE_BY_DEFAULT\020\000\022\036"
    "\n\032CONNECTION_CLOSE_BY_CLIENT\020\001\022\035\n\031CONNEC"
    "TION_CLOSE_STOP_SVR\020\002\022\036\n\032CONNECTION_CLOS"
    "E_EXCEPTION\020\003\"2\n\007AuthReq\022\n\n\002id\030\001 \002(\r\022\014\n\004"
    "auth\030\002 \002(\r\022\r\n\005token\030\003 \001(\t\"\031\n\007AuthRsp\022\016\n\006"
    "result\030\001 \002(\r\"\240\001\n\010GateAuth\022\013\n\003cmd\030\001 \002(\r\022\036"
    "\n\007authReq\030\002 \001(\0132\r.gate.AuthReq\022\036\n\007authRs"
    "p\030\003 \001(\0132\r.gate.AuthRsp\"G\n\013GateAuthCMD\022\022\n"
    "\016GATE_NEED_AUTH\020\001\022\021\n\rGATE_AUTH_REQ\020\002\022\021\n\r"
    "GATE_AUTH_RSP\020\003", 615);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "gate.proto", &protobuf_RegisterTypes);
  GateConnection::default_instance_ = new GateConnection();
  AuthReq::default_instance_ = new AuthReq();
  AuthRsp::default_instance_ = new AuthRsp();
  GateAuth::default_instance_ = new GateAuth();
  GateConnection::default_instance_->InitAsDefaultInstance();
  AuthReq::default_instance_->InitAsDefaultInstance();
  AuthRsp::default_instance_->InitAsDefaultInstance();
  GateAuth::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_gate_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_gate_2eproto {
  StaticDescriptorInitializer_gate_2eproto() {
    protobuf_AddDesc_gate_2eproto();
  }
} static_descriptor_initializer_gate_2eproto_;

// ===================================================================

const ::google::protobuf::EnumDescriptor* GateConnection_EventType_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return GateConnection_EventType_descriptor_;
}
bool GateConnection_EventType_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const GateConnection_EventType GateConnection::EVENT_CONNECTED;
const GateConnection_EventType GateConnection::EVENT_CLOSE;
const GateConnection_EventType GateConnection::EVENT_DATA;
const GateConnection_EventType GateConnection::EventType_MIN;
const GateConnection_EventType GateConnection::EventType_MAX;
const int GateConnection::EventType_ARRAYSIZE;
#endif  // _MSC_VER
const ::google::protobuf::EnumDescriptor* GateConnection_ConnectionCloseReason_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return GateConnection_ConnectionCloseReason_descriptor_;
}
bool GateConnection_ConnectionCloseReason_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const GateConnection_ConnectionCloseReason GateConnection::CONNECTION_CLOSE_BY_DEFAULT;
const GateConnection_ConnectionCloseReason GateConnection::CONNECTION_CLOSE_BY_CLIENT;
const GateConnection_ConnectionCloseReason GateConnection::CONNECTION_CLOSE_STOP_SVR;
const GateConnection_ConnectionCloseReason GateConnection::CONNECTION_CLOSE_EXCEPTION;
const GateConnection_ConnectionCloseReason GateConnection::ConnectionCloseReason_MIN;
const GateConnection_ConnectionCloseReason GateConnection::ConnectionCloseReason_MAX;
const int GateConnection::ConnectionCloseReason_ARRAYSIZE;
#endif  // _MSC_VER
#ifndef _MSC_VER
const int GateConnection::kEventFieldNumber;
const int GateConnection::kIdxFieldNumber;
const int GateConnection::kIpFieldNumber;
const int GateConnection::kPortFieldNumber;
const int GateConnection::kReasonFieldNumber;
const int GateConnection::kUidFieldNumber;
#endif  // !_MSC_VER

GateConnection::GateConnection()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:gate.GateConnection)
}

void GateConnection::InitAsDefaultInstance() {
}

GateConnection::GateConnection(const GateConnection& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:gate.GateConnection)
}

void GateConnection::SharedCtor() {
  _cached_size_ = 0;
  event_ = 1;
  idx_ = 0u;
  ip_ = 0u;
  port_ = 0u;
  reason_ = 0u;
  uid_ = GOOGLE_ULONGLONG(0);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

GateConnection::~GateConnection() {
  // @@protoc_insertion_point(destructor:gate.GateConnection)
  SharedDtor();
}

void GateConnection::SharedDtor() {
  if (this != default_instance_) {
  }
}

void GateConnection::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* GateConnection::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return GateConnection_descriptor_;
}

const GateConnection& GateConnection::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_gate_2eproto();
  return *default_instance_;
}

GateConnection* GateConnection::default_instance_ = NULL;

GateConnection* GateConnection::New() const {
  return new GateConnection;
}

void GateConnection::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<GateConnection*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  if (_has_bits_[0 / 32] & 63) {
    ZR_(idx_, reason_);
    event_ = 1;
  }

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool GateConnection::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:gate.GateConnection)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .gate.GateConnection.EventType event = 1;
      case 1: {
        if (tag == 8) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::gate::GateConnection_EventType_IsValid(value)) {
            set_event(static_cast< ::gate::GateConnection_EventType >(value));
          } else {
            mutable_unknown_fields()->AddVarint(1, value);
          }
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_idx;
        break;
      }

      // required uint32 idx = 2;
      case 2: {
        if (tag == 16) {
         parse_idx:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &idx_)));
          set_has_idx();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_ip;
        break;
      }

      // optional uint32 ip = 3;
      case 3: {
        if (tag == 24) {
         parse_ip:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &ip_)));
          set_has_ip();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_port;
        break;
      }

      // optional uint32 port = 4;
      case 4: {
        if (tag == 32) {
         parse_port:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &port_)));
          set_has_port();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_reason;
        break;
      }

      // optional uint32 reason = 5;
      case 5: {
        if (tag == 40) {
         parse_reason:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &reason_)));
          set_has_reason();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(48)) goto parse_uid;
        break;
      }

      // optional uint64 uid = 6;
      case 6: {
        if (tag == 48) {
         parse_uid:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &uid_)));
          set_has_uid();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:gate.GateConnection)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:gate.GateConnection)
  return false;
#undef DO_
}

void GateConnection::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:gate.GateConnection)
  // required .gate.GateConnection.EventType event = 1;
  if (has_event()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->event(), output);
  }

  // required uint32 idx = 2;
  if (has_idx()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->idx(), output);
  }

  // optional uint32 ip = 3;
  if (has_ip()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->ip(), output);
  }

  // optional uint32 port = 4;
  if (has_port()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(4, this->port(), output);
  }

  // optional uint32 reason = 5;
  if (has_reason()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(5, this->reason(), output);
  }

  // optional uint64 uid = 6;
  if (has_uid()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(6, this->uid(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:gate.GateConnection)
}

::google::protobuf::uint8* GateConnection::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:gate.GateConnection)
  // required .gate.GateConnection.EventType event = 1;
  if (has_event()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->event(), target);
  }

  // required uint32 idx = 2;
  if (has_idx()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->idx(), target);
  }

  // optional uint32 ip = 3;
  if (has_ip()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->ip(), target);
  }

  // optional uint32 port = 4;
  if (has_port()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(4, this->port(), target);
  }

  // optional uint32 reason = 5;
  if (has_reason()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(5, this->reason(), target);
  }

  // optional uint64 uid = 6;
  if (has_uid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(6, this->uid(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:gate.GateConnection)
  return target;
}

int GateConnection::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required .gate.GateConnection.EventType event = 1;
    if (has_event()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->event());
    }

    // required uint32 idx = 2;
    if (has_idx()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->idx());
    }

    // optional uint32 ip = 3;
    if (has_ip()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->ip());
    }

    // optional uint32 port = 4;
    if (has_port()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->port());
    }

    // optional uint32 reason = 5;
    if (has_reason()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->reason());
    }

    // optional uint64 uid = 6;
    if (has_uid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->uid());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void GateConnection::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const GateConnection* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const GateConnection*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void GateConnection::MergeFrom(const GateConnection& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_event()) {
      set_event(from.event());
    }
    if (from.has_idx()) {
      set_idx(from.idx());
    }
    if (from.has_ip()) {
      set_ip(from.ip());
    }
    if (from.has_port()) {
      set_port(from.port());
    }
    if (from.has_reason()) {
      set_reason(from.reason());
    }
    if (from.has_uid()) {
      set_uid(from.uid());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void GateConnection::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GateConnection::CopyFrom(const GateConnection& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GateConnection::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void GateConnection::Swap(GateConnection* other) {
  if (other != this) {
    std::swap(event_, other->event_);
    std::swap(idx_, other->idx_);
    std::swap(ip_, other->ip_);
    std::swap(port_, other->port_);
    std::swap(reason_, other->reason_);
    std::swap(uid_, other->uid_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata GateConnection::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = GateConnection_descriptor_;
  metadata.reflection = GateConnection_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int AuthReq::kIdFieldNumber;
const int AuthReq::kAuthFieldNumber;
const int AuthReq::kTokenFieldNumber;
#endif  // !_MSC_VER

AuthReq::AuthReq()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:gate.AuthReq)
}

void AuthReq::InitAsDefaultInstance() {
}

AuthReq::AuthReq(const AuthReq& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:gate.AuthReq)
}

void AuthReq::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  id_ = 0u;
  auth_ = 0u;
  token_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

AuthReq::~AuthReq() {
  // @@protoc_insertion_point(destructor:gate.AuthReq)
  SharedDtor();
}

void AuthReq::SharedDtor() {
  if (token_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete token_;
  }
  if (this != default_instance_) {
  }
}

void AuthReq::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* AuthReq::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return AuthReq_descriptor_;
}

const AuthReq& AuthReq::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_gate_2eproto();
  return *default_instance_;
}

AuthReq* AuthReq::default_instance_ = NULL;

AuthReq* AuthReq::New() const {
  return new AuthReq;
}

void AuthReq::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<AuthReq*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  if (_has_bits_[0 / 32] & 7) {
    ZR_(id_, auth_);
    if (has_token()) {
      if (token_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        token_->clear();
      }
    }
  }

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool AuthReq::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:gate.AuthReq)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 id = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &id_)));
          set_has_id();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_auth;
        break;
      }

      // required uint32 auth = 2;
      case 2: {
        if (tag == 16) {
         parse_auth:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &auth_)));
          set_has_auth();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_token;
        break;
      }

      // optional string token = 3;
      case 3: {
        if (tag == 26) {
         parse_token:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_token()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->token().data(), this->token().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "token");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:gate.AuthReq)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:gate.AuthReq)
  return false;
#undef DO_
}

void AuthReq::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:gate.AuthReq)
  // required uint32 id = 1;
  if (has_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->id(), output);
  }

  // required uint32 auth = 2;
  if (has_auth()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->auth(), output);
  }

  // optional string token = 3;
  if (has_token()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->token().data(), this->token().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "token");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->token(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:gate.AuthReq)
}

::google::protobuf::uint8* AuthReq::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:gate.AuthReq)
  // required uint32 id = 1;
  if (has_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->id(), target);
  }

  // required uint32 auth = 2;
  if (has_auth()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->auth(), target);
  }

  // optional string token = 3;
  if (has_token()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->token().data(), this->token().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "token");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->token(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:gate.AuthReq)
  return target;
}

int AuthReq::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint32 id = 1;
    if (has_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->id());
    }

    // required uint32 auth = 2;
    if (has_auth()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->auth());
    }

    // optional string token = 3;
    if (has_token()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->token());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void AuthReq::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const AuthReq* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const AuthReq*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void AuthReq::MergeFrom(const AuthReq& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_id()) {
      set_id(from.id());
    }
    if (from.has_auth()) {
      set_auth(from.auth());
    }
    if (from.has_token()) {
      set_token(from.token());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void AuthReq::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AuthReq::CopyFrom(const AuthReq& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AuthReq::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void AuthReq::Swap(AuthReq* other) {
  if (other != this) {
    std::swap(id_, other->id_);
    std::swap(auth_, other->auth_);
    std::swap(token_, other->token_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata AuthReq::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = AuthReq_descriptor_;
  metadata.reflection = AuthReq_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int AuthRsp::kResultFieldNumber;
#endif  // !_MSC_VER

AuthRsp::AuthRsp()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:gate.AuthRsp)
}

void AuthRsp::InitAsDefaultInstance() {
}

AuthRsp::AuthRsp(const AuthRsp& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:gate.AuthRsp)
}

void AuthRsp::SharedCtor() {
  _cached_size_ = 0;
  result_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

AuthRsp::~AuthRsp() {
  // @@protoc_insertion_point(destructor:gate.AuthRsp)
  SharedDtor();
}

void AuthRsp::SharedDtor() {
  if (this != default_instance_) {
  }
}

void AuthRsp::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* AuthRsp::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return AuthRsp_descriptor_;
}

const AuthRsp& AuthRsp::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_gate_2eproto();
  return *default_instance_;
}

AuthRsp* AuthRsp::default_instance_ = NULL;

AuthRsp* AuthRsp::New() const {
  return new AuthRsp;
}

void AuthRsp::Clear() {
  result_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool AuthRsp::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:gate.AuthRsp)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 result = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &result_)));
          set_has_result();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:gate.AuthRsp)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:gate.AuthRsp)
  return false;
#undef DO_
}

void AuthRsp::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:gate.AuthRsp)
  // required uint32 result = 1;
  if (has_result()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->result(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:gate.AuthRsp)
}

::google::protobuf::uint8* AuthRsp::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:gate.AuthRsp)
  // required uint32 result = 1;
  if (has_result()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->result(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:gate.AuthRsp)
  return target;
}

int AuthRsp::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint32 result = 1;
    if (has_result()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->result());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void AuthRsp::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const AuthRsp* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const AuthRsp*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void AuthRsp::MergeFrom(const AuthRsp& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_result()) {
      set_result(from.result());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void AuthRsp::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AuthRsp::CopyFrom(const AuthRsp& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AuthRsp::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void AuthRsp::Swap(AuthRsp* other) {
  if (other != this) {
    std::swap(result_, other->result_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata AuthRsp::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = AuthRsp_descriptor_;
  metadata.reflection = AuthRsp_reflection_;
  return metadata;
}


// ===================================================================

const ::google::protobuf::EnumDescriptor* GateAuth_GateAuthCMD_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return GateAuth_GateAuthCMD_descriptor_;
}
bool GateAuth_GateAuthCMD_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const GateAuth_GateAuthCMD GateAuth::GATE_NEED_AUTH;
const GateAuth_GateAuthCMD GateAuth::GATE_AUTH_REQ;
const GateAuth_GateAuthCMD GateAuth::GATE_AUTH_RSP;
const GateAuth_GateAuthCMD GateAuth::GateAuthCMD_MIN;
const GateAuth_GateAuthCMD GateAuth::GateAuthCMD_MAX;
const int GateAuth::GateAuthCMD_ARRAYSIZE;
#endif  // _MSC_VER
#ifndef _MSC_VER
const int GateAuth::kCmdFieldNumber;
const int GateAuth::kAuthReqFieldNumber;
const int GateAuth::kAuthRspFieldNumber;
#endif  // !_MSC_VER

GateAuth::GateAuth()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:gate.GateAuth)
}

void GateAuth::InitAsDefaultInstance() {
  authreq_ = const_cast< ::gate::AuthReq*>(&::gate::AuthReq::default_instance());
  authrsp_ = const_cast< ::gate::AuthRsp*>(&::gate::AuthRsp::default_instance());
}

GateAuth::GateAuth(const GateAuth& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:gate.GateAuth)
}

void GateAuth::SharedCtor() {
  _cached_size_ = 0;
  cmd_ = 0u;
  authreq_ = NULL;
  authrsp_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

GateAuth::~GateAuth() {
  // @@protoc_insertion_point(destructor:gate.GateAuth)
  SharedDtor();
}

void GateAuth::SharedDtor() {
  if (this != default_instance_) {
    delete authreq_;
    delete authrsp_;
  }
}

void GateAuth::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* GateAuth::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return GateAuth_descriptor_;
}

const GateAuth& GateAuth::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_gate_2eproto();
  return *default_instance_;
}

GateAuth* GateAuth::default_instance_ = NULL;

GateAuth* GateAuth::New() const {
  return new GateAuth;
}

void GateAuth::Clear() {
  if (_has_bits_[0 / 32] & 7) {
    cmd_ = 0u;
    if (has_authreq()) {
      if (authreq_ != NULL) authreq_->::gate::AuthReq::Clear();
    }
    if (has_authrsp()) {
      if (authrsp_ != NULL) authrsp_->::gate::AuthRsp::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool GateAuth::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:gate.GateAuth)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 cmd = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &cmd_)));
          set_has_cmd();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_authReq;
        break;
      }

      // optional .gate.AuthReq authReq = 2;
      case 2: {
        if (tag == 18) {
         parse_authReq:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_authreq()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_authRsp;
        break;
      }

      // optional .gate.AuthRsp authRsp = 3;
      case 3: {
        if (tag == 26) {
         parse_authRsp:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_authrsp()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:gate.GateAuth)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:gate.GateAuth)
  return false;
#undef DO_
}

void GateAuth::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:gate.GateAuth)
  // required uint32 cmd = 1;
  if (has_cmd()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->cmd(), output);
  }

  // optional .gate.AuthReq authReq = 2;
  if (has_authreq()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->authreq(), output);
  }

  // optional .gate.AuthRsp authRsp = 3;
  if (has_authrsp()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->authrsp(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:gate.GateAuth)
}

::google::protobuf::uint8* GateAuth::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:gate.GateAuth)
  // required uint32 cmd = 1;
  if (has_cmd()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->cmd(), target);
  }

  // optional .gate.AuthReq authReq = 2;
  if (has_authreq()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->authreq(), target);
  }

  // optional .gate.AuthRsp authRsp = 3;
  if (has_authrsp()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, this->authrsp(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:gate.GateAuth)
  return target;
}

int GateAuth::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint32 cmd = 1;
    if (has_cmd()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->cmd());
    }

    // optional .gate.AuthReq authReq = 2;
    if (has_authreq()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->authreq());
    }

    // optional .gate.AuthRsp authRsp = 3;
    if (has_authrsp()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->authrsp());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void GateAuth::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const GateAuth* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const GateAuth*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void GateAuth::MergeFrom(const GateAuth& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_cmd()) {
      set_cmd(from.cmd());
    }
    if (from.has_authreq()) {
      mutable_authreq()->::gate::AuthReq::MergeFrom(from.authreq());
    }
    if (from.has_authrsp()) {
      mutable_authrsp()->::gate::AuthRsp::MergeFrom(from.authrsp());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void GateAuth::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GateAuth::CopyFrom(const GateAuth& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GateAuth::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  if (has_authreq()) {
    if (!this->authreq().IsInitialized()) return false;
  }
  if (has_authrsp()) {
    if (!this->authrsp().IsInitialized()) return false;
  }
  return true;
}

void GateAuth::Swap(GateAuth* other) {
  if (other != this) {
    std::swap(cmd_, other->cmd_);
    std::swap(authreq_, other->authreq_);
    std::swap(authrsp_, other->authrsp_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata GateAuth::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = GateAuth_descriptor_;
  metadata.reflection = GateAuth_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace gate

// @@protoc_insertion_point(global_scope)
