#!/bin/sh
set +x
GEN_DIR=gen
CUR_DIR=`pwd`
function sync_restable_metas()
{
	#cp xls convert
	echo -e "syncing res table metas ..."
	cp res/*.proto ../tools/xlsconverter/meta/
	##################################################
	cd ${CUR_DIR}/../tools/xlsconverter
	echo "`pwd`"
	python ./converter.py run
	cd ${CUR_DIR}
	##################################################
	mv ../tools/xlsconverter/cpp/* ${GEN_DIR}/res/ 2>/dev/null
	cp ../tools/xlsconverter/meta/* res/
}
function sync_restable_files()
{
	#cp xls convert
	echo -e "syncing res table files ..."
	mkdir -p ${GEN_DIR}/res/
	mkdir -p res/
	mv ../tools/xlsconverter/cpp/* ${GEN_DIR}/res/ 2>/dev/null
	cp ../tools/xlsconverter/meta/* res/
}
function generate_proto_buffer_cpp()
{
	for dir in `ls` ;do
		if [[ -d $dir ]];then
			if [[ ${dir} == "gen" ]];then
				continue
			fi
			mkdir -p ${GEN_DIR}/${dir}
			proto_inc_file=${GEN_DIR}/${dir}/include.h
			#echo "${proto_inc_file}"
			echo '#pragma once' > $proto_inc_file		
			echo '//generate by generate.sh do not edit this file' >> $proto_inc_file
			echo "//generate time : `date`" >> $proto_inc_file
			proto_inc_init_dummy=$(echo -e "\nnamespace ${dir}\n{\n\tinline void init_proto_dummy()\n\t{\n")
			#echo -e "${proto_inc_init_dummy}\n"
			for proto in $(ls ${dir}/*.proto 2> /dev/null) ;do
				if [[ -f $proto ]];then
						execstring="protoc --cpp_out=${GEN_DIR} ${proto}"
						echo "generate proto buffer file [${proto}] [${execstring}]..."
						$(${execstring})
						proto_name=${proto#*/}
						proto_name=${proto_name%.*}
						echo "#include \"${proto_name}.pb.h\"" >> $proto_inc_file
						#EG. protobuf_AssignDesc_db_2fAccount_2eproto
						proto_inc_init_dummy+=$(echo -e "\n\t\tprotobuf_AddDesc_${dir}_2f${proto_name}_2eproto();\n")
				fi
			done
			proto_inc_init_dummy+=$(echo -e "\n\t}\n};\n")
			echo -e "${proto_inc_init_dummy}" >> ${proto_inc_file}
			echo " " >> $proto_inc_file
		fi
	done
}

######################################################################
sync_restable_metas
generate_proto_buffer_cpp
sync_restable_files



