#!/bin/sh
set +x
GEN_DIR=gen
#cp xls convert
cp ../tools/xlsconverter/cpp/* ${GEN_DIR}/res/
cp ../tools/xlsconverter/meta/* res/

for dir in `ls` ;do
	if [[ -d $dir ]];then
		if [[ $dir == "res" || ${dir} == "gen" ]];then
			continue
		fi
		proto_inc_file=${GEN_DIR}/${dir}/include.h
		#echo "${proto_inc_file}"
		echo '#pragma once' > $proto_inc_file		
		echo '//generate by generate.sh do not edit this file' >> $proto_inc_file
		echo "//generate time : `date`" >> $proto_inc_file

		mkdir -p ${GEN_DIR}/${dir}
		for proto in $(ls ${dir}/*.proto 2> /dev/null) ;do
			if [[ -f $proto ]];then
					echo "generate proto buffer file [${proto}] ..."	
					protoc --cpp_out=${GEN_DIR} ${proto}
					proto_name=${proto#*/}
					proto_name=${proto_name%.*}
					echo "#include \"${proto_name}.pb.h\"" >> $proto_inc_file
			fi
		done
		echo " " >> $proto_inc_file
	fi
done

